<?php

/**
 * @file
 * Contains commerce_momo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_momo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_momo module.
    case 'help.page.commerce_momo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module integrate MoMo Payment Platform to commerce payment system.') . '</p>';
      return $output;

    default:
  }
}
